# Web scrapping to obtain data for Neighbourhood income-CMHA(Source)

## Vancouver

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL of the target webpage
url = 'https://www03.cmhc-schl.gc.ca/hmip-pimh/en/TableMapChart/TableMatchingCriteria?GeographyType=MetropolitanMajorArea&GeographyId=2410&CategoryLevel1=Population%2C%20Households%20and%20Housing%20Stock&CategoryLevel2=Household%20Income&ColumnField=HouseholdIncomeRange&RowField=Neighbourhood&SearchTags%5B0%5D.Key=Households&SearchTags%5B0%5D.Value=Number&SearchTags%5B1%5D.Key=Statistics&SearchTags%5B1%5D.Value=Ranges'

# Make a GET request to the webpage
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table in the webpage
table = soup.find('table')

# Extract headers
headers = [header.text.strip() for header in table.find_all('th')]
# Ensure the first header is 'Neighbourhood' and remove any empty headers
headers = ['Neighbourhood'] + [h for h in headers[1:] if h]

# Extract rows
rows = []
for row in table.find_all('tr')[1:]:  # Skip the header row
    # Get row label from the first column
    row_label = row.find('th').text.strip() if row.find('th') else ''
    
    # Extract cell data
    cells = [cell.text.strip() for cell in row.find_all('td')]
    
    # Combine the row label with the cells
    if len(cells) == len(headers) - 1:  # Adjust for row label
        rows.append([row_label] + cells)
    else:
        # If the number of cells does not match, pad or truncate as needed
        cells.extend([''] * (len(headers) - 1 - len(cells)))  # Pad if too few cells
        rows.append([row_label] + cells[:len(headers) - 1])  # Truncate if too many cells

# Create a DataFrame
df = pd.DataFrame(rows, columns=headers)

# Filter columns to include only up to one column after 'Total'
if 'Total' in df.columns:
    total_index = df.columns.get_loc('Total')  # Find the index of 'Total'
    df = df.iloc[:, : total_index + 2]  # Include one column after 'Total'

    # Example of renaming by assigning to columns
df.columns = ['Neighborhood',
              'less than $20,000',
              'Income $20,000 - $39,999', 
              'Income $40,000 - $59,999', 
              'Income $60,000 - $79,999', 
              'Income $80,000 - $99,999', 
              'Income $100,000 and Over', 
              'Total', 
              ]  # Add additional names as necessary

# Save to CSV
df.to_csv('vancouver_neighborhood_data_filtered.csv', index=False)
print("Data saved to vancouver_neighborhood_data_filtered.csv")

# Display the DataFrame for verification
(df)

Data saved to vancouver_neighborhood_data_filtered.csv

,Neighborhood,"less than $20,000","Income $20,000 - $39,999","Income $40,000 - $59,999","Income $60,000 - $79,999","Income $80,000 - $99,999","Income $100,000 and Over",Total
0,Vancouver,"59,895","135,830","135,375","130,095","115,715","466,405","1,043,320"
1,Ambleside,335,900,685,585,360,"1,135","4,000"
2,Anmore/Belcarra/Metro Vancouver North,30,50,110,150,130,"1,070","1,545"
3,Capital Hill/Brentwood,"1,185","2,145","1,945","1,955","1,845","6,610","15,680"
4,Cedar Cottage,670,"1,800","1,735","1,735","1,415","6,200","13,565"
...,...,...,...,...,...,...,...,...
66,West End/Stanley Park South,235,690,695,505,400,870,"3,410"
67,Westside Heights,745,"1,835","1,890","1,830","1,440","6,220","13,960"
68,Westside/Kerrisdale Remainder,"1,640","2,540","2,355","2,120","1,845","11,395","21,890"
69,Whalley,"1,120","3,350","3,965","4,010","3,680","12,150","28,275"
70,White Rock,640,"1,880","1,750","1,565","1,160","3,745","10,735"

## Toronto

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL of the target webpage
url = 'https://www03.cmhc-schl.gc.ca/hmip-pimh/en/TableMapChart/TableMatchingCriteria?GeographyType=MetropolitanMajorArea&GeographyId=2270&CategoryLevel1=Population%2C%20Households%20and%20Housing%20Stock&CategoryLevel2=Household%20Income&ColumnField=HouseholdIncomeRange&RowField=Neighbourhood&SearchTags%5B0%5D.Key=Households&SearchTags%5B0%5D.Value=Number&SearchTags%5B1%5D.Key=Statistics&SearchTags%5B1%5D.Value=Ranges'
#https://www03.cmhc-schl.gc.ca/hmip-pimh/en/TableMapChart/TableMatchingCriteria?GeographyType=MetropolitanMajorArea&GeographyId=2410&CategoryLevel1=Population%2C%20Households%20and%20Housing%20Stock&CategoryLevel2=Household%20Income&ColumnField=HouseholdIncomeRange&RowField=Neighbourhood&SearchTags%5B0%5D.Key=Households&SearchTags%5B0%5D.Value=Number&SearchTags%5B1%5D.Key=Statistics&SearchTags%5B1%5D.Value=Ranges'

# Make a GET request to the webpage
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table in the webpage
table = soup.find('table')

# Extract headers
headers = [header.text.strip() for header in table.find_all('th')]
# Ensure the first header is 'Neighbourhood' and remove any empty headers
headers = ['Neighbourhood'] + [h for h in headers[1:] if h]

# Extract rows
rows = []
for row in table.find_all('tr')[1:]:  # Skip the header row
    # Get row label from the first column
    row_label = row.find('th').text.strip() if row.find('th') else ''
    
    # Extract cell data
    cells = [cell.text.strip() for cell in row.find_all('td')]
    
    # Combine the row label with the cells
    if len(cells) == len(headers) - 1:  # Adjust for row label
        rows.append([row_label] + cells)
    else:
        # If the number of cells does not match, pad or truncate as needed
        cells.extend([''] * (len(headers) - 1 - len(cells)))  # Pad if too few cells
        rows.append([row_label] + cells[:len(headers) - 1])  # Truncate if too many cells

# Create a DataFrame
df = pd.DataFrame(rows, columns=headers)

# Filter columns to include only up to one column after 'Total'
if 'Total' in df.columns:
    total_index = df.columns.get_loc('Total')  # Find the index of 'Total'
    df = df.iloc[:, : total_index + 2]  # Include one column after 'Total'

    # Example of renaming by assigning to columns
df.columns = ['Neighborhood',
              'less than $20,000',
              'Income $20,000 - $39,999', 
              'Income $40,000 - $59,999', 
              'Income $60,000 - $79,999', 
              'Income $80,000 - $99,999', 
              'Income $100,000 and Over', 
              'Total', 
              ]  # Add additional names as necessary

# Save to CSV
df.to_csv('toronto_neighborhood_data_filtered.csv', index=False)
print("Data saved to Toronto_neighborhood_data_filtered.csv")

# Display the DataFrame for verification
(df)

Data saved to Toronto_neighborhood_data_filtered.csv

,Neighborhood,"less than $20,000","Income $20,000 - $39,999","Income $40,000 - $59,999","Income $60,000 - $79,999","Income $80,000 - $99,999","Income $100,000 and Over",Total
0,Toronto,"108,855","264,185","268,775","272,180","252,230","1,096,245","2,262,475"
1,Agincourt/Malvern,"1,340","4,625","5,225","5,595","5,050","16,355","38,190"
2,Ajax/Pickering,"1,440","4,975","6,500","7,925","8,105","43,965","72,910"
3,Alderwood,120,525,560,535,475,"2,565","4,790"
4,Aurora,655,"1,630","2,015","2,340","2,140","12,730","21,505"
...,...,...,...,...,...,...,...,...
130,Woodbine-Lumsden,160,475,385,380,355,"1,615","3,380"
131,Wychwood,315,965,735,650,640,"2,460","5,770"
132,Yonge-Eglinton,350,725,870,720,445,"2,875","5,995"
133,Yonge-St. Clair,440,770,935,920,740,"3,400","7,205"
134,Yorkdale-Glen Park,355,"1,095","1,060",945,790,"2,590","6,835"